kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
  namespace: igloo
data:
  traefik.toml: |+
    #logLevel = "DEBUG"

    defaultEntryPoints = ["http", "https"]

    # Web interface of Traefik
    [web]
    address = ":8080"
    [web.metrics.prometheus]

    # Enable Kubernetes ingress integration
    [kubernetes]

    # Force HTTPS
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    # Let's encrypt configuration
    [acme]
      email="brady@odicro.com"
      storage="/etc/traefik/acme.json"
      entryPoint="https"
      acmeLogging=true
      onDemand=true
      onHostRule=true
      dnsProvider="zeit.world"
    [acme.dnsChallenge]
      provider = "zeit.world"
