# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: litellm
spec:
  name: litellm
  owner: litellm
  cluster:
    name: igloo-pg
  databaseReclaimPolicy: retain
