# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-role-secret
    template:
      data:
        username: "{{ .DB_USER }}"
        password: "{{ .DB_PASS }}"
  dataFrom:
    - extract:
        key: litellm
