---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpackerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      unpackerr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/unpackerr/unpackerr
              tag: 0.14.5@sha256:dc72256942ce50d1c8a1aeb5aa85b6ae2680a36eefd2182129d8d210fce78044
            env:
              TZ: America/Los_Angeles
              UN_WEBSERVER_METRICS: true
              UN_WEBSERVER_LOG_FILE: /logs/webserver.log
              UN_ACTIVITY: true
              UN_SONARR_0_URL: http://sonarr.servarr.svc.cluster.local:8989
              UN_SONARR_0_PATHS_0: /media/downloads/qbittorrent/tv-sonarr
              UN_RADARR_0_URL: http://radarr.servarr.svc.cluster.local:7878
              UN_RADARR_0_PATHS_0: /media/downloads/qbittorrent/radarr
            envFrom:
              - secretRef:
                  name: unpackerr-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
        pod:
          restartPolicy: Never
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: unpackerr
        ports:
          http:
            port: 5656
    serviceMonitor:
      app:
        serviceName: unpackerr
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      logs:
        type: emptyDir
      media:
        type: nfs
        server: 100.68.189.69  # helios64.shark-tone.ts.net
        path: /export/Glacier02/Media
        globalMounts:
          - path: /data/nas-media/Downloads/qbittorrent
            subPath: Downloads/qbittorrent
