# - - - - - - - - - - - - - - - - - - - -
#    Presence Based
# - - - - - - - - - - - - - - - - - - - -
- alias: Turn On Lights on Arrival
  trigger:
    - entity_id: group.all_devices
      platform: state
      to: home
  condition:
    - after: sunset
      after_offset: -01:00:00
      condition: sun
  action:
    - data:
        entity_id: group.living_room_lights
      service: light.turn_on
