---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbtools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tagging:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: 0 * * * *
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 3600
        initContainers:
          tag: &container
            image:
              repository: ghcr.io/buroa/qbtools
              tag: v0.21.2@sha256:33da584c9d71bb2d8b9931995c41599bef1fdebf52cf5408cdd09175069f299a
            env:
              QBITTORRENT_HOST: &qbittorrent_host qbittorrent.servarr.svc.cluster.local
              QBITTORRENT_PORT: &qbittorrent_port "8080"
              SABNZBD_HOST: sabnzbd.servarr.svc.cluster.local
              SABNZBD_PORT: 8080
            envFrom:
              - secretRef:
                  name: qbtools-secret
            args:
              - tagging
              - --added-on
              - --expired
              - --last-activity
              - --sites
              - --unregistered
              - --not-linked
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
              - --config
              - /config/config.yaml
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                memory: 128Mi
                cpu: 25m
              limits:
                memory: 256M
        containers:
          expired:
            <<: *container
            args:
              - prune
              - --exclude-category
              - manual
              - --exclude-category
              - cross-seed
              - --exclude-category
              - music
              - --exclude-tag
              - added:1d
              - --include-tag
              - expired
              - --with-data
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
          unregistered:
            <<: *container
            args:
              - prune
              - --exclude-category
              - manual
              - --exclude-category
              - cross-seed
              - --exclude-category
              - music
              - --exclude-tag
              - added:1d
              - --include-tag
              - unregistered
              - --with-data
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
        pod:
          restartPolicy: Never
      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: "@daily"
          suspend: true
        containers:
          app:
            <<: *container
            args:
              - orphaned
              - --exclude-pattern
              - "*/manual/*"
              - --exclude-pattern
              - "*/cross-seed/*"
              - --exclude-pattern
              - "*_unpackerred*"
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
        pod:
          restartPolicy: Never
      reannounce:
        containers:
          app:
            <<: *container
            args:
              - reannounce
              - --process-seeding
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
      limiter:
        containers:
          app:
            <<: *container
            args:
              - limiter
              - --max-line-speed-mbps
              - "100"
              - --max-percent
              - "0.8"
              - --limit-percent
              - "0.4"
              - --interval
              - "5"
              - --server
              - *qbittorrent_host
              - --port
              - *qbittorrent_port
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    persistence:
      secret-file:
        type: secret
        name: qbtools-config-secret
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      media:
        type: nfs
        server: 100.68.189.69  # helios64.shark-tone.ts.net
        path: /export/Glacier02/Media
        globalMounts:
          - path: /data/nas-media/Downloads/qbittorrent
            subPath: Downloads/qbittorrent
