ansible_become_pass: ENC[AES256_GCM,data:mKzKXRW7LDUD,iv:TxjrlWkWcNNGyHvTdUIneilynBG4I7fYyRzkN6WGiZ4=,tag:V/7Ti2dM1qisn+Js71jrvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17fxvltsgxtzvpjnsjfuuwf5jddvrhwvaafzcgw98gx0l9l2mx4xqlczmym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTGpLc2F5WjNxVEFDNkt0
            L2FZZjVhV2JKQ2p0MEFJbVlSWjY3L1pqSGxzCkEzSHpKZnJXNnY0UGl1cDl4T3BG
            NzBSQXNBTEgwY1l5b2lsME5rUWVzbTgKLS0tIDcxUDdlY1B4RFl1UFNHaUJwVjds
            dGh4R3JsVTZ2N083a29iTittUTMrWjQKj8FY4l1WqaJcigxFFwHgGD0ddzCnX9E/
            18OhTc4yo/gvlqy59JNCBUiHSrjRG6WgzR4FBucqSiGQumrdFkHEnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T08:14:14Z"
    mac: ENC[AES256_GCM,data:V9pCF8F9Bk9CXI12XpoxJTTrXVae3YE3HaOz6dUG8YZZ7OgmydQgPFqRKAmAf6F441Bv7l8N2ay1G/GUTn2uFtGMBJx2QcynD3dMvp1AHgY0rpH8RtcRliysfoZVLp4ybU+n2Hu8x1jT+KoTw0w5z16nfb3ehDEE/+LQh9sq2/Y=,iv:DZM74D5kicu3FJfbU0sPKLIJVRHIIxHnVY5zEhnYzfE=,tag:g7yH2SV+4pwR2rhghESgoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
