apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:6GIWvuM6UkrD4w43g93Bk2QWRlei21oGtXopBSP1InkViign4SaIU7FDobxNzTPb0SssRROfrUIPKjGq7/xj,iv:j2WQZ4xRXrYW2E8DlepjyhDA1uabH7uC/YT/nG1GGJU=,tag:oye4f1mshqawNPqigMjpaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYVpZYTkxTHM0V1VubFRz
            UXJkY28rdmZuMU14UnZEcXZpTnFxNVduZ1NnCml3YjgxZHlubjhSOXAvY0VLb2lB
            UUc0TjQxSk9yODBiNWdHZ3J6NVFrNkEKLS0tIDlUSVNsSGltMDZtU0ZFNUdPRzQz
            QXdOSGZZN3RPTlp4TGtvdWJQbnU3encKjL1UBeJbirGfm8IRfIRPsGNxuRuqZZ/w
            2n8zgM6DWbiBOZyusY8YQ+0WsDXGKYvyj6x/CGQT1lKoraQ4oMfENw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T18:38:29Z"
    mac: ENC[AES256_GCM,data:C5wyvD3skbrmtWcO5MbbPjtSyojiIasvBACfQWFqmBEqxX2Db+csHZKKcHjWfHWNVri/Mm7pUUlKqRymuNu1lpg3i4W8062ul5IeGp6eJVanwNFGsXcpCcTke3MVJNnIhTEOPIK3yo9S6gFcAbfhBAn3izNqw1sYzN8iraNly8Y=,iv:pSGRj+x+aSAkDKowpf0b57oqYcPN/UW9KVZBkzC2duM=,tag:xhqBybXcggOH+InB3ZD7SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
