apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1rk8T2RsYTimBjyn6ubQr5q/lPayT4oRQ57y+ZZ6SZyWRKYg,iv:t1V9nqWxJTIG6lnIkzbsY+Jzw47AJR/rVbuSu3Omjnc=,tag:LOx8HwtMYPVq9LLkvK5fsQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:5MniNnbV+v2lGBo1CUdhC0pazJGJqE2EeIMRXrZ+0UOXG1x6z/n47iegQ44WkId2+T2/D2Cqkh0F/S5S+YbsBSSj4pij9sYlve7g2IBcXFNRUYruAPDcoJbBrJaW2duoAzh7sUx4JC3ydy2OV8CupEGNc9aXsn71+uXGyaqkj6goYx8eCWBFDWYteSuzuFYVD1lPHUShHC65yeY6dV79DKhq3yuHGMg2kCiR+qgQ4w==,iv:KX4UI+qfQ3amtghMJqIFqi4Tq5QgiWoBSRyFGx+oCac=,tag:Aqs1XGFMVto5acAhTQ00kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWjA0UnZaZ2MrOUk1SW5m
            bXR4QTJwSkMyZWFwNk1BdDRuRlVBdjMwL3ljCkV6cEN5ZUlKdGtYTFZESTlZdmF3
            aFl0TXpuQXhRVHFMSjRQRGJpSXloV1EKLS0tIC9EdzZjOUwzbTQ3c2NRQlBORWoy
            TDlCQmc5NmxvRkFCN0FjSFZNRG4wb0UK4BYvVaGQqidxu5TSk+95GkdV5jjRDwwS
            Sy8fvSKskgfN9SHL4zLAB6HWkTpqhYkFJOxCzKjTkyWruUOkqWtQ7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T05:09:10Z"
    mac: ENC[AES256_GCM,data:MrdE6mMqfnP2H0qYjAPIaOfDOeQ8ZLSjK5jY94eCTHny3kS7t9VGQRk2Qa3MXdMl/NvNKQzZChb0CGSmSDVKHb54+oHjmsidbbBDslfvH9o72XKFTkQKJ2bvPkGTDD9Um05XXlvQ45MG4oAPcZXOUG18/TSVfn9+Pq04yVzwxec=,iv:5JQJPpUYNOOh46YTXRRbhGBzR8nKf7IRs8/eorfLGzw=,tag:VJAowFhyhgx4SWgHebM5JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
