apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Zx8BfeoJ4EZ1gjA1IBG5MRlIeKCKP9Df,iv:u70vjFKzXFQGsERHc3JIwPG2aHL4fkXBuPisurFbI7U=,tag:JRC5AGcm/ZG2AXVVoZOsNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age143pqluyd0cecdvdmz6g5tqevq028syjw3asdlzukuqqm5yrvcdksacwtgg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbzRxRER6cytscERYWnBz
            YlNVRG4yRXFsV1ZXVzBsSVVjdk16d0E1aG40CkZ3VzNXT0FSYXUrZGpkY2JVM1Br
            SFdYNEw1TThXdFJZMmwxaENmZDE0UVkKLS0tIDFPSFAvbzVQdmZ3TXQ2L2FHOGZP
            Z2poYTVjWWlJUDRzbWNvbWd3VENsM0UKXj4pMGKn0C++gdhlyDdT5FQX944PeVpj
            qg7vkwUFXgsx8GhRx/fKEccOZYF7ZGiSm7AhoxIvOuQLlAw9gwXIFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T05:02:26Z"
    mac: ENC[AES256_GCM,data:YfMSl4/IwJa9omk+Wfs9It37FFpFLugjGCmRmEdaauwmMuTAASlXIYb3c36ih9P0gkNiK/T4W5k/pU1iEV5V9JNpWkIpvFzFx71XjytfICYFA1qFXqdbg9LyxveMK6hvPw543mNfRDsHDB5LDgtbKUdVPaH2btLyf5CpU1kzneo=,iv:qBwkgGWQkmusftALwptcyfmr9lMVe/6lsIQAxJRIHog=,tag:aG/kjrr4aXpAnCVpxsQoYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
