apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age143pqluyd0cecdvdmz6g5tqevq028syjw3asdlzukuqqm5yrvcdksacwtgg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NHNjWEtMaFoxTHBsNTJR
            WDkveXZzck9qVHcyWE9jZVNuaG42ckhyL1c0CnIyaDBzckI5dmZKZWtFY0Y3d1ph
            N0pLMjVxMHBicWpWdDVDMVUzUWp6ODgKLS0tIEp5OTNzeU90QTJMemZnWHhTZXVC
            Y1JITjc0K3F3QXpYNnhGbzNydEtzdDgK/3OmyatbJIOo3hCvXr6f11OFvTezeeaa
            YZeQBFjmrjaBh9qg/Mz+quWHGwnMDv6oRdyMEHL2UtoGinFr0qsCbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T05:57:57Z"
    mac: ENC[AES256_GCM,data:/pR+4noMmlrpHumND5SZyr5UwbLW2FK40NA4jiNa1DjzFe3GLgQ+rV3vZBFPvoZKoQ7C8y8zMKaHklAN9xZsmwwgB9MMbsUFYUZh/gYMkhAQ4ppYRjzKh8CW7PD1agzpnsziSxVD0tPWfOAxBez48WsFk00QGAejP9VlFnn3o7A=,iv:szrZk5Y0K+iPdQQtTdj6elR+A9BCwgqTkyMr3rQvglM=,tag:Xop5D6r9jitd7CEh93f1AQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
