# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-secret
    template:
      data:
        DATABASE_URL: "postgresql://{{ .DB_USER }}:{{ .DB_PASS }}@igloo-pg-rw.database.svc.cluster.local:5432/{{ .DB_NAME }}"
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        POOLSIDE_API_KEY: '{{ .POOLSIDE_API_KEY }}'
  dataFrom:
    - extract:
        key: litellm
