---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: glance-secret
    template:
      data:
        GLANCE_LATITUDE: "{{ .GLANCE_LATITUDE }}"
        GLANCE_LONGITUDE: "{{ .GLANCE_LONGITUDE }}"
        GLANCE_SECRET_KEY: "{{ .GLANCE_SECRET_KEY }}"
        GLANCE_ADMIN_PASS: "{{ .GLANCE_ADMIN_PASS }}"
  dataFrom:
    - extract:
        key: glance
