# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:YwGStmP6HMel6zyr036v0TSDuFq/uoRsdb5GtCJ3+HE=,iv:IUrzLVK4J6WFvu/FKyzagvNh4Wpsp2NUbyzcVB40TN0=,tag:HeyZjLMiRBivybIorm3B4A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OGVVQkhPWjZBWWpXNloz
        bVU0T05LWGN4bjhaamRkWE9OU0tvNllxZVZrCi9RbVc0dkRFTUhLMFN2akRQRUZZ
        bWJobHQyTWNVamtYcHZiM1pqZitCeFEKLS0tIDc0RUVsdGYxaSt2T0pWSDBzVjRk
        b3d6NVFDMUxBaitPK2haYVM2NGd3Q3MKG8gW5U1sZ8pke2GozZ9GJyH84i1szqQa
        WwV4Yn4UBT1U3IjGIM4bjiRss5VBfL78W9o7d/vSJrG1FWmDMeHsPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-29T15:52:32Z"
  mac: ENC[AES256_GCM,data:ziKdvaFkeVM9/3ETO7i3DPEHiaw/mLI4yTVE3a67xVRZzKXh858oFqxmFAI+6Ofc6tonZDlHrA5kw6sS50gqnFuw37ALKHQS6VmRKuIc5dZhpjbYE25zY0m3YJ7rYAqaSLHYs0XAZsXuIY4Ynt0LaQellQwQxet2EGXZ6nonpig=,iv:APRCXrKEgo2Nb/Y78b3KhB/ZELo3628jGfgskN6wx98=,tag:Thc+mUXq6AoHpOWAOVt50Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
