---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
badge:
  font: Verdana.ttf
  size: 12

metrics:
  - name: talos_version
    query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
    label: version_id
    title: Talos

  - name: kubernetes_version
    query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
    label: git_version
    title: Kubernetes

  - name: flux_version
    query: label_replace(flux_instance_info, "revision", "$1", "revision", "v(.+)@sha256:.+")
    label: revision
    title: Flux

  - name: cluster_node_count
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    colors:
      - {color: "green", min: 0, max: 9999}
    title: Nodes
