# - - - - - - - - - - - - - - - - - - - -
#    Core Configuration
# - - - - - - - - - - - - - - - - - - - -
homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat_key
  longitude: !secret lon_key
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

# - - - - - - - - - - - - - - - - - - - -
#    Core Enables
# - - - - - - - - - - - - - - - - - - - -
# Show links to resources in log and frontend
introduction:
# Enable frontend and configuration panels
config:
# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Enables support for tracking state changes over time
history:
# View all events in a logbook
logbook:
# Enables a map showing the location of tracked devices
map:
# Track the sun
sun:
# Text to speech
tts:
  - platform: google_translate
# Cloud
cloud:
#iframe setup in dashboard
panel_custom:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://hassio.local:3218

# - - - - - - - - - - - - - - - - - - - -
#    Extras
# - - - - - - - - - - - - - - - - - - - -
# Weather prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
# - - - - - - - - - - - - - - - - - - - -
#    Includes
# - - - - - - - - - - - - - - - - - - - -
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
