---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flame
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: flame-secret
    template:
      data:
        FLAME_PASSWORD: "{{ .FLAME_PASSWORD }}"
        PASSWORD: "{{ .FLAME_PASSWORD }}"
        PUSHOVER_TOKEN: "{{ .FLAME_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: flame
    - extract:
        key: pushover
