apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: igloo
  labels:
    app: mosquitto
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mosquitto
  externalIPs:
    - 192.168.0.101
  selector:
    app: mosquitto
