apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ESFea3sDDNVEW96LhD7KT8J/A7PFZ/JXK7gjAU3sbNL5IAym+WLSdg==,iv:dpDAK4+wLEMlJTJlbNqqaT+Mo25nbktkjTJ76VSEO38=,tag:2Toc9z/ZQT1+9Zj73F0/SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaElnN1ZnSHpBcTNuY3JX
            K1BYVkJTV1k3dDVUZC9HYXk1WllSdExwN2xJCndFZEJ6QW9UWnYzU0xhNmlzV3pO
            QlpSZHZSa2RGc3N0Q2p0NVM0SDhscEEKLS0tIGpTdGYvbUJsNUlmaHBMM3I2OUJM
            aDJlS3J6SlJjbTFkaHZYV0hQYzBScFkKpnIzm87/sBThI7leRryG5oZAVyrhTra9
            OWCHD5nFWZuKqlsuAE9He8tHRvqBFgGmX0n8CQsEfGL71QV+hnel3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T04:35:30Z"
    mac: ENC[AES256_GCM,data:QPrmZii3nHWjVNrwcmDgHrfzMJjnyzpVCbfbJt2KYsm7b0VXiEy7EFxkQipn5iEv3boTuSH2W0nbpIBJK1NY8FoBi05xhpRC598SNKAUIYL94FzSb/bN7mnIKPtu/GRKUtJKAN35gT+HIHkZLEl4jD1eglv5CzNFawu5oFs1TTg=,iv:8BO6JM3HLcHJTpiL092BN015asPkko30RhTJ20fXLvE=,tag:sfT01o17guyuO9R/QFz1dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
