apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vmg5K3hCR1YyZWxtUisx
            UmxteVhyTjhJYWxVQ20vZXZIa0tob1VkblZrCjkzL1A5YS9KV3dCekdDZmd2ZUVk
            TEZMYUVhVVo3WUFOM2loc0FmZEZGQ2sKLS0tIHBrcG14dThYODhiOGxsWDhzdTNv
            MXB0TXcvZ2pKVHJ3NEdJd3Z4aVl4R1EK5x8jNnV0Wb20tEcDNV+qsBBZjA4vAQLc
            +olYKyFrCvt5NeZnn+CnyEt2mcbOpwOQn5Jvp1P8fQhE9MP1MougCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T20:35:21Z"
    mac: ENC[AES256_GCM,data:N5EhPvYjZ3Iw/yDIAlmDTpzKA3HSq4cxJq8v+0oDyH+l4kdtYFTUAtHO7x0DeOrBTGWV8ShXvptlymogWxhqkPk4ZbwIwKs4alvoUm7OjbDUpvdrfc6h+fm0r0xkifN7ti5STsxyYl+2x4/GBCgDD3EKPSMuuMDnWud5RpyxKAQ=,iv:wM9AtcJMIrFqcw7s7l+dKk6XtVYj1CptilgJ7Nl0PxE=,tag:87lXDkD59cY9oQZwbQvt3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
