apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:pAvkLF7LavGfNW/1yKlRiDdWoYAWYlXjpB5P8Ogzo+UJvxUcDaV4Ow==,iv:1UbdS/TFgZX6Hb05uzQ+pGHE4tJXU8FQqR0DJRwNCbs=,tag:gnDMs/5W8TO15Ewv1xDJFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age143pqluyd0cecdvdmz6g5tqevq028syjw3asdlzukuqqm5yrvcdksacwtgg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOEJMY29BVHNrWE5mYzkv
            bGF6SzJPaVl3L05wcWY3OS9Vd0FGdk1lbXhRCnlReXBXdCtxclViWlRZaXEyelND
            U1R1QklDMC9VbGFtQ0ZuQmxSdlRjUFUKLS0tIGxCSWgwdFUycjBCSWdkZTd1K2Zq
            dWh2ZklaR0dVZmFmZXdQUGpSRHJ0ODQKuZEtG/S75NEHobqWTRFgpShws8quzveI
            HPYt+Ysmd0Y02ev4lO2OlH9wzkQXTlnGSpgxT+L7Ih3k/BRSF5mUBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T05:02:28Z"
    mac: ENC[AES256_GCM,data:ESyZDJbPygkD4ZOVB0+WObddDDALVpqMOtHHvSTu9NF2WuBQwUr6aOJ0tYJpCEZOAVCMvTRkEfFZCoKYo6xtB0mi12eh9ck4SG4MdPfNh93jAzsAp9h4Tuh6kmJnID0mbn3wPD9AgiozRTgzWIbMwly6ULv6Q4WxKbDCkuVkvEY=,iv:VL1WYspQYU3ijDKGSSwKzVudssF4RwUV9q6af8129X8=,tag:XUn+0dlWNpiCggx29qhsyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
