apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVFZYdXJ5cTZndnNnd1RS
            ZDhhTDNqaGZoRU5iZDVKMEtRQVA2WUNGbUEwCklZMDkyV3haZ2xlWERUbnBHMDIy
            Z0JuT1h2QjBCeFRneitkSVk2emRHRzAKLS0tIG5VaWlBVXMvVEZOamRTeEE3RWUr
            Y0U4ZWJ2RGNyMnlBUW04eHFGOHM4bEkK/0KxX6/dysuTvcUhiCJvNDQz525dwNGI
            YC10Y24JNElgCkoFGhgJ3N8oSsjd/t+OOC/iYCePsKFOaB3+g7NL+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T04:53:35Z"
    mac: ENC[AES256_GCM,data:/lUj2VOzGlmyvEEKSGHXZz1FCRSvuevw8LA1QMSY8azra0cpamHh30K9E7Sf+saVfh/G5RBn40Z1FhSXioADMkcwyFRgMzzVUDLMKUbBuLlr+seG9ig1u0Lbzt+MrWMfVo0I/zL4bBEKAI5brKawvrUe7UmPwEVWDn6mWOndtec=,iv:OXNwstpQA/i7o4/Rug66H4UgKc+a4zVfxgA8vmF2fdw=,tag:ynSj7GZPlNLBZtE81jRkPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
