apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2wg2gx+rkfOSgMAnu9QsXT57ZfphNXTcbgg3bubod6WGf/8qcRNrTw==,iv:TrFUow9VYkWUv7xyAvGo7FAMdhjkiNb3hfA+0w7Psj4=,tag:GuN32pkssgU/jdABpaXxNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbXF5aEk3eHR6VGlINisr
            OUsvTmtSRERTZERoZUJZWjJNNXFEQkJZZ2hNCldSTHozK2JCTUFBd096T2k0YVpZ
            ZDdEQXBxcDVaK2U4MTQ1Ky80UjhwMWsKLS0tIEhlUGVNM3FXME5FR1M3aEc5UDhs
            YVBCdTljbEIyaVNJK0RFSjU3Q2pUWDQKh5Tl6aLOPJ5o+yMRXCcl3B3huwFdR56t
            JFm81DVWG4rph6L12bWlP+aB/cqFew1WYIrWZ6aqxkv/bkDk5SmalA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-15T02:04:43Z"
    mac: ENC[AES256_GCM,data:2GUF8tSBneM31rQfDxE9MTjiysx4bu7FSHvKmV2j9QOa5yiMDu1JZwlOszpNDbO33uIvRBQT781nle4LyqoZVAWpEokZzry8fTIut91SOibzXyzvY1sM0yoTVYXcSCWkRIvZEurLjJkb5vM6OZ2saYiXdOeWd4bKC9Rzs6ZiU5Q=,iv:5QqOs0K0h346t5z27/bFao6IjA/zOsrXRoJJXB25lb0=,tag:4XOob5qMdLzFhD2SAWAzgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
