apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: igloo
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
