---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tuppr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tuppr-notifications-secret
    template:
      data:
        url: pover://{{ .PUSHOVER_USER_KEY }}@{{ .TUPPR_PUSHOVER_TOKEN }}
  dataFrom:
    - extract:
        key: tuppr
    - extract:
        key: pushover
