---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: tuppr
  interval: 1h
  values:
    replicaCount: 2
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    notification:
      enabled: true
      secretName: tuppr-notifications-secret
      secretKey: url
      titleTemplate: "Talos upgrade starting: {{ .Node }}"
      messageTemplate: "{{ .Node }}: {{ .CurrentVersion }} -> {{ .TargetVersion }} (plan {{ .Plan }})"
    monitoring:
      dashboards:
        enabled: true
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: true
