---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cross-seed-secret
    template:
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            delay: 30,
            duplicateCategories: true,
            flatLinking: false,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDirs: [
              "/data/nas-media/Downloads/qbittorrent/complete/cross-seed"
            ],
            linkType: "hardlink",
            matchMode: "safe",
            outputDir: "/config",
            port: Number(process.env.CROSS_SEED_PORT),
            qbittorrentUrl: "http://qbittorrent.servarr.svc.cluster.local:8080",
            radarr: [
              "http://radarr.servarr.svc.cluster.local:7878/?apikey={{ .RADARR_API_KEY }}",
            ],
            skipRecheck: true,
            sonarr: [
              "http://sonarr.servarr.svc.cluster.local:8989/?apikey={{ .SONARR_API_KEY }}",
            ],
            torznab: [],
            useClientTorrents: true
          };
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: radarr
    - extract:
        key: sonarr
