apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mosquitto
  namespace: igloo
  labels:
    app: mosquitto
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: slipperypenguin/rpi-mosquitto:v3
          imagePullPolicy: IfNotPresent
          command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/mosquitto.conf"]
          volumeMounts:
          - mountPath: "/mosquitto"
            name: "config"
      volumes:
        - name: config
          configMap:
            name: mosquitto-conf
