---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system # Required for Renovate lookups
spec:
  interval: 5m
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
