---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app amd-gpu-node-labeller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: amd-device-plugin
      namespace: kube-system
  values:
    controllers:
      amd-gpu-node-labeller:
        serviceAccount:
          name: *app
        type: daemonset
        containers:
          app:
            image:
              repository: docker.io/rocm/k8s-device-plugin
              tag: labeller-1.25.2.5@sha256:cd0decbe8e44ff8906fe9c3163b1ae102bcffc23e85edd6213f393beaa8ad78e
            workingDir: /root
            command: ["/root/k8s-node-labeller"]
            args:
              - "-logtostderr=true"
              - "-stderrthreshold=INFO"
              - "-v=5"
              - "-vram"
              - "-cu-count"
              - "-simd-count"
              - "-device-id"
              - "-family"
            env:
              TZ: America/Los_Angeles
              DS_NODE_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                cpu: 25m
                memory: 10Mi
              limits:
                memory: 100Mi
            securityContext:
              privileged: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: asus-node-01
      priorityClassName: system-node-critical
    service:
      app:
        enabled: false
        controller: amd-gpu-node-labeller
    persistence:
      sys:
        enabled: true
        type: hostPath
        hostPath: /sys
      dev:
        enabled: true
        type: hostPath
        hostPath: /dev
