---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: unifi-dns
  namespace: network # Required for Renovate lookups
spec:
  interval: 12h
  url: https://kubernetes-sigs.github.io/external-dns
