---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    template:
      data:
        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .QB_GLUETUN_API_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .PROTON_QB_WG_ADDRESSES }}"
        WIREGUARD_ENDPOINT_IP: "{{ .PROTON_QB_VPN_ENDPOINT_IP }}"
        WIREGUARD_PRIVATE_KEY: "{{ .PROTON_QB_WG_PRIVATE_KEY }}"
        WIREGUARD_PUBLIC_KEY: "{{ .PROTON_QB_WG_PUBLIC_KEY }}"
  dataFrom:
    - extract:
        key: qbittorrent
    - extract:
        key: proton
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-gluetun-secret
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .QB_GLUETUN_API_KEY }}"
  dataFrom:
    - extract:
        key: qbittorrent
