# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:I9U94pSh9NSU8ZTiIyx7CIlMZAybjCZaeftw38kMwUa5JQWZdU09+Q==,iv:P0akS7mLLWYijaLpTCbBEtXPMDsg5YM3LJIpHvUBCe4=,tag:fZrNOp/sHmHS+0h8he/Gww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeWNmc3RRcktBek9xYlNH
        SnhzbFlUTExma1hDMlc1RnpOU0VXVTRjOUU0CnNBMGxOMzUrN3ZkaEVNcnFmMHJT
        MWFEbTNPaHdwc0VCdVdkVk5SZkZVeHcKLS0tIE85K2V1Z2FsQXQ5ZzRoOXZRNHpn
        bzJUQmFWRmZDZVVVeEhQandHU09acjQKNxZdBiTb4y5xIT/DQsNRj3nOfZATbBE6
        wxBAJCYhQWVFyB8O3UF6VrSWPXW5Q/KgUWIGxfKuuvj49YoXU6Fpyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-29T15:52:32Z"
  mac: ENC[AES256_GCM,data:Yqk3nKoFTVWXi0x28hOgdTUYSHyYeeZaCp6ZuGD8CH3cXVUYy99FwcArbhuq04clv+/OHvn50qi0oSBKP2dwm0LliJhhQKu6MCIqJTjaWbCuTWGuwQPZOxc3JYQDc6YVJb1LL0zJ+aK93DlTWDdEVkKTpoQP/JiZ38xh81BatBs=,iv:3jp87PNC0v5TlDOQpfUdScfZz4ALnMlWlT7ghHiYX/Y=,tag:1xluJgGRGpD4gV3QprwfbA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
