# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.10.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.33.2

clusterName: "igloo"
endpoint: https://192.168.20.6:6443

clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"

additionalApiServerCertSans: &sans
  - "192.168.20.6"
  - "100.67.118.115"
  - "127.0.0.1"
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "mbp-node-01"
    ipAddress: "192.168.20.228"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e810eb45767cfabcdb7a45e389eee803045af7a9467faebde5c91164861883a
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f4:34:f0:e4:73:46"
        dhcp: false
        addresses:
          - "192.168.20.228/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
        vip:
          ip: "192.168.20.6"
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=$TS_AUTHKEY
          - TS_ROUTES=10.96.0.0/16,10.69.0.0/16,192.168.20.0/24,192.168.1.0/24
          - TS_ACCEPT_DNS=true
  - hostname: "mbp-node-02"
    ipAddress: "192.168.20.176"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/240f33ba108b4418f67b9f69c9246178a8bc06228b9064d815e20da4c837b4b4
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:e0:4c:b3:4b:f6"
        dhcp: false
        addresses:
          - "192.168.20.176/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=$TS_AUTHKEY
          - TS_ROUTES=10.96.0.0/16,10.69.0.0/16,192.168.20.0/24,192.168.1.0/24
          - TS_ACCEPT_DNS=true
  - hostname: "dell-node-01"
    ipAddress: "192.168.20.129"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e810eb45767cfabcdb7a45e389eee803045af7a9467faebde5c91164861883a
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "48:4d:7e:eb:43:40"
        dhcp: false
        addresses:
          - "192.168.20.129/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=$TS_AUTHKEY
          - TS_ROUTES=10.96.0.0/16,10.69.0.0/16,192.168.20.0/24,192.168.1.0/24
          - TS_ACCEPT_DNS=true
  - hostname: "dell-node-02"
    ipAddress: "192.168.20.224"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6e810eb45767cfabcdb7a45e389eee803045af7a9467faebde5c91164861883a
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "54:bf:64:88:5a:cc"
        dhcp: false
        addresses:
          - "192.168.20.224/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.20.1"
        mtu: 1500
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=$TS_AUTHKEY
          - TS_ROUTES=10.96.0.0/16,10.69.0.0/16,192.168.20.0/24,192.168.1.0/24
          - TS_ACCEPT_DNS=true

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-udev.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/machine-features.yaml"

