apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EiZctjFDCgA=,iv:oI1lcyDljqqLmyrIXLpTeIcEE89IdMHQmrgeR5y7LdA=,tag:HfmRv4wXIGaJOTm9dnPncQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:yinBWHubazc5RSGURuk=,iv:j7hgnSTyX1jsCKXscP6a1mWtP36qHRxXw6qCQa7LUUs=,tag:NKkCS4R+7vX+5bxGVtvwRQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:d8J2f9HIeDSlyvWhJ/dZY3eCV1XmtHFEd/VmsVs4wlDUIn9V,iv:+9FGEKr0OzVh2JyKR+GB8OoYJWDHl1TWgrgSoRZu++g=,tag:O8Kdx1yYwHa7EOwy4tgf3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcnp2VVZrUVpGRTNvYXNP
            Zm5vQ296UjZoYzIrZUt2UHJYNmptcUV4ZEhzCkNhRDVOdUNoRFM2dlpCQjhGdThp
            R0IvZUNyY1dRbWhlMGRTblNPWVhWazgKLS0tIHpPVXJrMjRjeE5wV3dZVldEUVlw
            aHhaRjBwNUVidmh1dHhpeGxRbkt2QmMKi7se+YS0pNo2W4YdyPdcy9LR6tA+nczf
            sxY0HtxiZ3U09ME+d+JTIK5scFX7MamcZA0lstaZu2AO3p/JmLsgEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-15T06:11:20Z"
    mac: ENC[AES256_GCM,data:CfKdiNEPVfJlj9FIcT2WZ89tTuxnIxlxU1ZT2CCxrUSJcc+eY9ZiTKKxYHjPXfn96nTLp0CJeWh/9ZFWPSt9EZ819ofiUX8n2OrBibapf+Nlot88+tnbIRXqGauoaxyA01qgoBa9lOzPmxiXd3/eCTCLeQtgEOXCM1qrP7Mc82Q=,iv:g9deepn82h4hVw6xjUf3zOX+pG+xGpgEp/XjuRhHsI0=,tag:zDv/NUQbi/ySXEPCwUBgmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
