apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:h+7KPUIqmRI1ReKe/vE=,iv:cxFBIpLMhb06qZ9knfWFI1oBb88XGwrL+/4dgvzwVak=,tag:80kg+9zmuPMKwN9mRUYEEQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:l7nSNa+l7xSLkHkwEKGYStWk20GjRufzTWW9Ak0BsgV1F10W,iv:PcCxc5/KY/KwAs4yr6+XNVdiaK0xDW3yYrUu4YILtCk=,tag:0aMQPdkGg0UW4JfvJd+MRQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dlg0Jq5hnOo=,iv:945ol7MDN+/INNqugyZKeyMywQnwG4tSunm9P7i57vs=,tag:PfifJYj/h09hRjBLhjm4HQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17fxvltsgxtzvpjnsjfuuwf5jddvrhwvaafzcgw98gx0l9l2mx4xqlczmym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNDBLS2FWcDluekcydFph
            RERaQzVGYTlMcFJoaU91UkVycW51V1ZMOFRRClR2b05YWkM0Rmx5WDh1OTQzYXo5
            MXJiRE5HeVNqc0I2SjBxdktqY0J1c1kKLS0tIHBLS1pzNDZLbjNhTWNBNEt0aDVq
            alk5SFlGT0tYYUNCSDJmUnBJSjA3QmMKbeqYsdbww9wqptB8v5kWOQh3upgle8Pu
            QhGauI5cUIL4ld0Ua/fjFqYpx5SxAiuaLlbv487uuG8BrskpfXiSsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T08:15:30Z"
    mac: ENC[AES256_GCM,data:7eTHFoz0dGhYcX4V9jaYfrbuNiU0oFszcY0/t3WqX0B8HE/9YRhuv8vFW/OTBnmjmk0ia6zfTm8c2GgUcudzPvcDp37r9zfpIX47wPgNZ/vguYRo82tuQzE1+tYIqVxN4XZ2wV9/166SCijxE62xgc6vrbHo43zLnj3p4J6GiSU=,iv:nvhwgLEHNbfB5DlQyXYBxZin9fRgAW4OoVFm/DTwaTY=,tag:oAu0is3176kdQkgA3HZiTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
