# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    template:
      data:
        DATABASE_URL: "postgresql://{{ .DB_USER }}:{{ .DB_PASS }}@igloo-pg-rw.database.svc.cluster.local:5432/{{ .DB_NAME }}"
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: open-webui
    - extract:
        key: litellm
