---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-client-check
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: unifi-client-check-secret
    template:
      data:
        PUSHOVER_TOKEN: "{{ .UNIFI_CC_PUSHOVER_APP_TOKEN }}"
        PUSHOVER_USER: "{{ .PUSHOVER_USER_KEY }}"
        UNIFI_CONTROLLER_USER: "{{ .UNIFI_CC_USER }}"
        UNIFI_CONTROLLER_PASSWORD: "{{ .UNIFI_CC_PASSWORD }}"
  dataFrom:
    - extract:
        key: unifi-client-check
    - extract:
        key: pushover
