---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./scrapeconfig.yaml
configMapGenerator:
  - name: jellyfin-json-exporter-config
    files:
      - jje.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
