apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:UzOzYV1/KsmfyXoruZ6tCNBLpIMNosdI8r4J0JvTH1s=,iv:SYawJ80NH/hHAaia65OWWDdr83wuDmfxTKJl9cm0o5U=,tag:VRaV3Kxctbcyre1jGsOK8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U3BhcVBNUlBneHdFZHBh
            NXV5ZVlNa0RMQVdXQVBRTHJVUXZ4UTlLUXk0CkRUbHd4bmk4VlRXUll1QzcyMmFQ
            TGU3S2g4NHpiekVibHRJdTliL0xvN0UKLS0tIEhqQmZMclBFK1U4MlRTNC9nNDNh
            Q0U0YlVaTWYrMmhMbjhJUi8zT2l2dDgKHwK9wFsAJwF5J02g/MBqWkhIg8T8QvsJ
            h9PEULBreVYsNi7nLb8tJucdofNSHr0LUcngZgO+g4gqkKaUJXD7HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T02:16:50Z"
    mac: ENC[AES256_GCM,data:6BXAGw+gviSgvxzfKoKp89EPbyN/Z1UkJY53/pJu+q5lBFjHttKNeaBs6APp1EYMJ7hjLxsHgmAPeAng10kKwziPzYF82/7rqp2nS0SXytoHyUgzHEFq0/F2YGs60maDahv6aleSZCU2RojUnyuREUJbYRhxo5U+GQ+1SVfJbmM=,iv:uWWFsmk4ZoTWMT6hZXvLQDIpGzyThnIsPwbdr7YdVEc=,tag:/jWhpcEXq+mxcQ1t8/iUPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
