# ref: https://grafana.com/docs/loki/latest/configure/
deploymentMode: SingleBinary
loki:
  auth_enabled: false
  analytics:
    reporting_enabled: false
  server:
    log_level: info
  commonConfig:
    replication_factor: 1
  compactor:
    working_directory: /var/loki/compactor/retention
    delete_request_store: filesystem
    retention_enabled: true
  ingester:
    chunk_encoding: snappy
  limits_config:
    retention_period: 14d
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-04-01" # quote
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  structuredConfig:
    ruler:
      enable_api: true
      enable_alertmanager_v2: true
      alertmanager_url: http://alertmanager-operated.observability.svc.cluster.local:9093
      storage:
        type: local
        local:
          directory: /rules
      rule_path: /rules/fake
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClass: openebs-hostpath
    size: 20Gi
gateway:
  replicas: 0
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
chunksCache:
  enabled: false
resultsCache:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false
sidecar:
  image:
    repository: ghcr.io/kiwigrid/k8s-sidecar
  rules:
    searchNamespace: ALL
