apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:zf/aTRjbQ/+HASFOTwAA7ZE4qYlp5ga9hmCiBz4pqVBWz5VkgM3jeA==,iv:8hmkALAQQwc5KzAwuhEqianOd4ycb36dYDmTNRh8HQk=,tag:d+AocQxPdi/ij8b7lGtb3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZFRTSWZUcElzazZPUEl0
            ZjlpQUQ0T3kxajlzS3NrTHA1eThiUmJtWW1nCmlyMmk0SU43L2xWSVJWaHN0elJG
            UTBqb0w2ZEhxMWdhTXFTQ0g1SUpvc1kKLS0tIGlyVEs4TW5MalJraURGV3h1aDRF
            ZlVZSmRUeHNqMngybE1STStiaVdNSXcKI23rMz/T69cM/93zkWKwrknP/1VLmVDi
            +7My0yBMeem4ojFzAG98B9yykOCID7A2y1ji6dj05gISfotoW2z0Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T01:44:03Z"
    mac: ENC[AES256_GCM,data:b4spI1bhHP62zi0IXB7rGeu4RdZk9aTCDBFZp/5wTgNgcLZC1FqYqtTB9FB695yQlXPGEYuuEVuZq/PtNyGut606GI9dC/kkq2ySEDv+Ro2ohqYg5hNs9RgYX0KRpe5grEF7eWlEua12LekPSlD43J9HF5/ERsqYxj50yuoPQt8=,iv:IUpm26DWrXdliXiPKFmzrYiIMtwO9+wKmXoLweprl3k=,tag:5xkYhkoW9kXMTDptbVA8Ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
