apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:+mkcy4fMatvYI5yX3ydYgup6G7X5s2BYMsn4BX1MwchG0xvNW/zorg==,iv:3Nz1IThVQaAK9tKDshlC42nL2nipwjFR09AbIFluoOE=,tag:7MnfNDqWxv1DCgiO7BC7iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2sz2tk9h82n8g0cygzet8q6h0z2xrs4r8jjym268sudgjwpqd3shvrvzm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHKzVmbkl1djNvWmVtMzdG
            a1ppRHhZQnV0aHZDVUNSOFhaeFdINXB6Um5RCkJvMHFndUlqeUxSRFNkMTVESS9m
            V3Q2SWJiNHJLMUh0YWtVUTg4bzZFdjAKLS0tIFlTUW9nYWlKWFpHcXc0OWhqVlBR
            ZTdpVDZNRHo5KzY4bzdGRVRMMWhaSWcKZfpRdgFqJQJj7+Wbf/IB3KRXntB1/P/J
            KYdrq1OChTMoJCHMPVXYGMRrYcfe3B5DWtnhyAt2djpLqfLaRa5ZAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-15T06:11:20Z"
    mac: ENC[AES256_GCM,data:o/jB2FCB8s1doXZl38IG3fSJrcw+SmZv4vtDaHwr4yzxiDOeZRt5cKTcN3/KVj3aa7jWU0tYXYVbEPIWw9kTO0NkBsOt6u+YTvmslmPyitMLG9Q134kAZv6XMxHiE4N7F8XU6iF/2fPUr+q8KoJ8Wm/QfSGcyKlYaixQJZlp1qg=,iv:EHcKA1bKOUWiTUyug6ST9zizdwnTa+x9Yn97mX/JQ/U=,tag:2qeCxSm8lwkZ9dKyRooxlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
