kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: svclb-traefik
  namespace: kube-system
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/svclb-traefik
  uid: 64bb2cf8-c2f6-11e9-b84e-b827eb1d08db
  resourceVersion: '2773'
  generation: 1
  creationTimestamp: '2019-08-20T02:58:31Z'
  labels:
    objectset.rio.cattle.io/hash: f31475152fbf70655d3c016d368e90118938f6ea
    svccontroller.k3s.cattle.io/nodeselector: 'false'
  annotations:
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/8yUQW/jNhCF/0oxZ8qRItmRBfRQJHsI2k0M29vLIghG5DhmTZECOVLXMPTfCyrZtdMkmwXawx49fPP0+M3QB9hpq6CCK6TG2RUxCMBW/0k+aGehAmzbcNZnIKAhRoWMUB3AYkNQQeilqRP2SBu9AzGWQ4synu26mpKwD0wNCJCekLWza91QYGxaqGxnjACDNZkQPV39F0kOxBOv3UQis6GJdmdbDFuoYJNnxcU0m55v6s1FOptOVS7TbKbyWUnzNMvKeV5uZoQgYizpLHtnDPnJLg8nbtYpCmRIsvPRFU0gGASgtY7HiN8No9XjtY/+IN4Uu78t+eSh30EFZ30mfvldW/XrinyvJb3b98T4SPd9+WvsBwGjYEkb8mQlBag+H54PeZzv0yYc470I0I23nxUXWM5zlcjzzSzJMpondVlQUpfnF1RnKi1VHSd+JFSx72i4GwSElmTEe5zAARpkuf3j2xpg277YrGEQwNS0BpnGlpNV/IHNes3y+1sSevmv2w8n6WMbakv+EeWT0tRJ6zwnZQoCdIMPsejRyi35s53RbUs+MXXVp5NsEoFH9dsOWxd44TxDVabi+MmvpeFOANn+tH21vLxf3C7XIKBH08VSmcIgvgmuPqzW94vl7fr2RLK+XLzUvOtyvTg5z9JJkU/Os8l8CjGXp+A6P27aYXhiseiMWTij5R4quN7cOF54CmTjH04g2XnN+0tnmb7wiBhbrLXRrOlxhEpB9RluPqzvf7v6eH0Dd8NwkukruaLI/yv8R4sj/aLIX+AvivzH+Eez/2EAr9n8FBO4i8+iaxUyrdgj08M+annfxlRLZ4y2D5/GcxDgn/0en/6XTxZ71AZrQ1Blw/jMGLkbvyk778nyTdfU5FdyS6ozpKBKBdix9lGH8KysKGhP6u2OJaHaQ5UOwz8BAAD//w2xIxr8BgAA
    objectset.rio.cattle.io/id: svccontroller
    objectset.rio.cattle.io/owner-gvk: '/v1, Kind=Service'
    objectset.rio.cattle.io/owner-name: traefik
    objectset.rio.cattle.io/owner-namespace: kube-system
  ownerReferences:
    - apiVersion: v1
      kind: Service
      name: traefik
      uid: 647a893d-c2f6-11e9-b84e-b827eb1d08db
      controller: true
spec:
  selector:
    matchLabels:
      app: svclb-traefik
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: svclb-traefik
        svccontroller.k3s.cattle.io/svcname: traefik
    spec:
      containers:
        - name: lb-port-80
          image: 'rancher/klipper-lb:v0.1.1'
          ports:
            - name: lb-port-80
              hostPort: 80
              containerPort: 80
              protocol: TCP
          env:
            - name: SRC_PORT
              value: '80'
            - name: DEST_PROTO
              value: TCP
            - name: DEST_PORT
              value: '80'
            - name: DEST_IP
              value: 10.43.21.95
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
        - name: lb-port-443
          image: 'rancher/klipper-lb:v0.1.1'
          ports:
            - name: lb-port-443
              hostPort: 443
              containerPort: 443
              protocol: TCP
          env:
            - name: SRC_PORT
              value: '443'
            - name: DEST_PROTO
              value: TCP
            - name: DEST_PORT
              value: '443'
            - name: DEST_IP
              value: 10.43.21.95
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  templateGeneration: 1
  revisionHistoryLimit: 10
