kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik
  namespace: kube-system
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/traefik
  uid: 647efff8-c2f6-11e9-b84e-b827eb1d08db
  resourceVersion: '475'
  generation: 1
  creationTimestamp: '2019-08-20T02:58:31Z'
  labels:
    app: traefik
    chart: traefik-1.64.0
    heritage: Tiller
    release: traefik
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
      release: traefik
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: traefik
        chart: traefik-1.64.0
        heritage: Tiller
        release: traefik
      annotations:
        checksum/config: 0432fce01d241cafbe45b2440c4e0fcd658160564c2b9139337e613a1eac6b8d
    spec:
      volumes:
        - name: config
          configMap:
            name: traefik
            defaultMode: 420
        - name: ssl
          secret:
            secretName: traefik-default-cert
            defaultMode: 420
      containers:
        - name: traefik
          image: 'traefik:1.7.9'
          args:
            - '--configfile=/config/traefik.toml'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: httpn
              containerPort: 8880
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: ssl
              mountPath: /ssl
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      serviceAccountName: traefik
      serviceAccount: traefik
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
