---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: openebs-rules
spec:
  groups:
    - name: openebs.rules
      rules:
        - alert: KubernetesVolumeOutOfDiskSpace
          expr: |
            kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes * 100 < 20
          for: 5m
          annotations:
            summary: >-
              Kubernetes Volume out of disk space (instance {{ $labels.instance }})
            description: >-
              Volume is almost full (< 20% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}
          labels:
            severity: warning
