---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Pre-pull Images"

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-job:
    name: Image Pull - Pre-Job
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get Changed Files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
        with:
          patterns: kubernetes/**/*

  extract:
    name: Image Pull - Extract Images
    if: ${{ needs.pre-job.outputs.changed-files != '[]' }}
    needs: pre-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branches: ["default", "pull"]
      fail-fast: false
    outputs:
      default: ${{ steps.images.outputs.default }}
      pull: ${{ steps.images.outputs.pull }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: "${{ matrix.branches == 'default' && github.event.repository.default_branch || '' }}"

      - name: Gather Images
        uses: docker://ghcr.io/allenporter/flux-local:v7.3.0
        with:
          args: >-
            get cluster
            --all-namespaces
            --path /github/workspace/kubernetes/flux/cluster
            --enable-images
            --only-images
            --output json
            --output-file images.json

      - name: Output Images
        id: images
        run: |
          echo "${{ matrix.branches }}=$(jq --compact-output '.' images.json)" >> $GITHUB_OUTPUT

          echo '## Branch ${{ matrix.branches }} images' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          jq '.' images.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  compare:
    name: Image Pull - Compare Images
    if: ${{ needs.extract.outputs.default != needs.extract.outputs.pull }}
    runs-on: ubuntu-latest
    needs: extract
    outputs:
      images: ${{ steps.compare.outputs.images }}
    steps:
      - name: Compare Images
        id: compare
        run: |
          images=$(jq --compact-output --null-input \
              --argjson f1 '${{ needs.extract.outputs.default }}' \
              --argjson f2 '${{ needs.extract.outputs.pull }}' \
              '$f2 - $f1' \
          )
          echo "images=${images}" >> $GITHUB_OUTPUT

          echo '## New images to Pull' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          echo $images | jq >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  pull:
    name: Image Pull - Pull Images
    if: ${{ needs.compare.outputs.images != '[]' }}
    runs-on: home-ops-runner
    needs: compare
    strategy:
      matrix:
        images: ${{ fromJSON(needs.compare.outputs.images) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Install talosctl
        run: curl -fsSL https://talos.dev/install | sh

      - name: Pull Image
        run: talosctl --nodes $NODE image pull ${{ matrix.images }}

  status:
    name: Image Pull - Success
    if: ${{ !cancelled() }}
    needs: pull
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
