name: lint

on:
  pull_request:
    push:
      branches:
      - master

jobs:
  lint-yaml:
    runs-on:
    - ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Lint YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: "./cluster"
        config_file: "./.github/yamllint.config.yaml"

  lint-shell:
    runs-on:
    - ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Lint shell scripts
      uses: reviewdog/action-shellcheck@v1
      with:
        path: "./hack"
        level: "error"

  lint-ansible:
    runs-on:
    - ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set up Python 3.X
      uses: actions/setup-python@v2
      with:
          python-version: '3.x'

    - name: Install test dependencies.
      run: pip3 install ansible-lint ansible

    - name: Lint Ansible
      run: ansible-lint
      with:
          file_or_dir: "./ansible/k3s-ansible/"
