apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  # chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.77.1.tgz
  # or any traefik version, like
  chart: https://kubernetes-charts.storage.googleapis.com/traefik-1.79.0.tgz
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    dashboard.enabled: "true"
    dashboard.domain: "traefik.lab.local"
    # dashboard.domain: "traefik.igloo.odicro.com"
    # dashboard.auth.basic.test: "$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
    acme:
      enabled: true
      challengeType: "dns-01"
      dnsProvider:
        name:  # name of the dns provider to use
        $name: # the configuration of the dns provider. See the following section for an example
      # variables that the specific dns provider requires
      domains:
        enabled: true
        domainsList:
          - main: "*.example.com" # name of the wildcard domain name for the certificate
          - sans:
            - "example.com" # OPTIONAL: Alternative name(s) for the certificate, if you want the same certificate for the root of the domain name for example
          - main: "*.example2.com" # name of the wildcard domain name for the certificate
